import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['300','400','600','700','800'],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "SmartSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
